name: welcome

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  welcome-message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: Beep boop beep... I am a real human... for real.\n\n
          Welcome to the RIOT community, we will try to address this as soon as we can.
          As I mentioned before, we are human and sometimes we get distracted with life.
          I can try to ping someone like this.\n\n
          ping @MrKevinWeiss\n\n
          Feel free to do the same for other [maintainers](https://github.com/orgs/RIOT-OS/teams/maintainers/members) if things are taking a while.
        pr-message: Beep boop beep... I am a real human... for real.\n\n
          Welcome to the RIOT community, we will try to review this as soon as we can.
          As I mentioned before, we are human and sometimes we get distracted with life.
          I can try to ping someone like this.\n\n
          ping @MrKevinWeiss\n\n
          Feel free to do the same for other [maintainers](https://github.com/orgs/RIOT-OS/teams/maintainers/members) if things are taking a while.
